[project]
name = "migration-pattern"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.9",
    "notebook>=7.4.7",
    "pandas>=2.3.3",
    "pyreadstat>=1.3.1",
]
